### ISSUE TITLE
Possible Issue?

### ISSUE THREAD

**Issue by m-erdemm** [blg604-proje/blg604-proje#1]
Hi,
I am not sure whether this is an issue or not. I've  followed the given installation guide and did not get any error during installation process. But when I run example codes, I observe black shadow like things on the ground and they move as the car moves or I look around with my mouse.  At this point I just want to know that is it possible to have some problems when I start training with this setup or not.
Thanks in advance,

**Note: I have the correct version of all required packages and my OS is Ubuntu 20.04**

![Screenshot from 2020-06-06 14-58-55](https://user-images.githubusercontent.com/37617174/83943994-05945280-a809-11ea-81e9-77294beef7fb.png)

**Comment by ferhatmelih** [comment]
Hi, thank you for detailed explanation. We will try to upload a patch to Simstar to solve this issue. Until then, it should not effect your sensory or control functions. So you can continue training.

**Comment by ferhatmelih** [comment]
This is solved with the OpenGL based version. You can find it in the link, under Linux folder. But standart version should work just fine computationally.
