### ISSUE TITLE
Dutch Grand Prix Angle Sensor

### ISSUE THREAD

**Issue by ljacobi** [blg604-proje/blg604-proje#10]
On the Dutch track, the value for simstar_obs['angle'] sensor jumps to extreme values, even though the car has not significantly changed its position. This problem does not exist on the Hungary track.

**Comment by ferhatmelih** [comment]
Hi,

I debugged and solved the error. It happens very briefly in Dutch track between 300-330 meters along the track. 
Thanks for noticing this. 
If you want to see how i did debugging, you can see debug/dutchAngle branch. I use the vehicle in keyboard mode and print out the road angle deviations. 

It is fixed now in master. You can pull the  latest repo.

**Comment by eray94** [comment]
Thanks a lot. 
We have also debug it in a same way and did a hotfix for this. Then opened this issue.
As Luis stated we checked it for Hungary and Dutch Grand Prix but we did not do it for Austria. As I understand you have already checked it for all tracks. So can we assume that, we can use this sensor for Austria Grand Prix as well ?

**Comment by ferhatmelih** [comment]
Yes. It is solved in the environment script. You can pull the latest environment. 
It is always better to double check, so please do. 

Thanks.
