### ISSUE TITLE
No visualization option during training

### ISSUE THREAD

**Issue by AkgunOnur** [blg604-proje/blg604-proje#2]
Hi,

Is there any option to turn off visualization of vehicle during the training procedure? If it is possible, the training procedure will take much less computation power

Thanks
Onur

**Comment by ferhatmelih** [comment]
Hi,  

There is an option to turn off visualization. Pressing **X** will turn off display. 
Thanks for the feedback.

**Comment by firatoncel** [comment]
Hi,

Pressing X only turns off display but rendering is still active. Is there any option to turn off rendering?

Thanks

**Comment by ferhatmelih** [comment]
I checked again, pressing X also turns off rendering.  
There is also a command line option that you can use mentioned in GymEnv/README.md file. 
  
    ./SimStar.sh -no-rendering-simstar=1

**Comment by ferhatmelih** [comment]
Just a reminder, there is an additional command explained in [ReadM](https://github.com/blg604-proje/blg604-proje/tree/master/GymEnv#no-rendering-mode) with which you can start simulation without opening a new window.
