### ISSUE TITLE
Hz and speed up in final race?

### ISSUE THREAD

**Issue by firatoncel** [blg604-proje/blg604-proje#3]
What will be the values of Hz and speed-up in final race as the dynamics of environment are changing drastically? Also, can you provide the test script as soon as possible?

**Comment by ferhatmelih** [comment]
this is a good point.  we are running some tests to finalize the optimal decision on environment sampling, Hz. And it will be shared once it is decided, along with a test script. 

thanks

**Comment by ferhatmelih** [comment]
10 Hz environment sampling seemed to give better results. This is why we chose that for final eval script. An example eval script is still added to Pytorch example.  However, in the actual race, lap time will be the final measure.

**Comment by firatoncel** [comment]
Austria track in eval script is not working for us. Austria pickle is not created properly. Thanks!

**Comment by ferhatmelih** [comment]
Hi, can you try installing the PythonAPI again?

`python setup.py install`

**Comment by firatoncel** [comment]
No luck, can you share the pickle? Thanks!

**Comment by ferhatmelih** [comment]
Hi. I uploaded the tracks as pickle files in GymEnv/tracks/*.pkl.

**Comment by firatoncel** [comment]
Thanks!

**Comment by ferhatmelih** [comment]
As stated in the final announcement, the evaluation for each agent will be done separately, therefore you can configure the environment sampling to the value that you get the best performance with. Please read [ReadMe](https://github.com/blg604-proje/blg604-proje/tree/master/GymEnv#syncronous-mode) if you decide to change this value.

**Comment by firatoncel** [comment]
According to our experience, it is far more easy to develop model at higher update frequencies. For us, it was quite challenging to develop a successful model at 10 Hz. Therefore, we think that it is not fair to change this evaluation criteria when it is this much close to the competition.

**Comment by ferhatmelih** [comment]
Okay. I will discuss this issue with the professor today. He can give better judgement and announce.
