### ISSUE TITLE
An issue about not functioning the enviroment

### ISSUE THREAD

**Issue by batu-robotics** [blg604-proje/blg604-proje#5]
We have a problem when setting up the simstar in Windows. We setup all the required packages under Anaconda environment, and thereafter downloading missing .dll files below, and finally setup the Unreal Engine from scratch, but unfortunately it gives fatal error? Afterwards we actually could not find what the problem is actually, so what would you suggest to overcome the problem? Many thanks.

**Comment by ferhatmelih** [comment]
which .dll files are giving the error? can you share here. 

There is a known issue in Windows that can be solved by installing the following library:

[Windows Library Download Link ](https://aka.ms/vs/16/release/vc_redist.x64.exe)

**Comment by batu-robotics** [comment]
First of all thank you for the .exe file. Actually, when I searched the crash log, three .dll files do not exist, being 'aqProf.dll, VtuneApi.dll, and VtuneApi32e.dll'. I setup the .exe file attached, unfortunately nothing changes
![error_message](https://user-images.githubusercontent.com/67713338/87591125-8ab83480-c6f0-11ea-864a-64b037786eea.jpg)

**Comment by ferhatmelih** [comment]
Thanks for detailed explanation. Can you please share the log file here?  SimStar.log

**Comment by batu-robotics** [comment]
Hereby attached, you may find the SimStar.log file, thanks
[SimStar.log](https://github.com/blg604-proje/blg604-proje/files/4936545/SimStar.log)

**Comment by ferhatmelih** [comment]
can you try running the simulator in server mode and see if you get the same error or not. 
Go to the location where SimStar.exe is located. In command prompt type 

`SimStar.exe -nullrhi`

Then try running the API test script or train script. 

If there is no problem, SimStar should be running in the background without a display.

**Comment by batu-robotics** [comment]
I did just we talked, but unfortunately got 'Fatal Error' again. I changed the SimStar version v.1.5.3.D into v.1.5.3.B, tried to run without a display, but nothing changes. Any other idea you would suggest? Many thanks for all your support.

**Comment by batu-robotics** [comment]
I thank to you for all your support. I've setup the env. on Linux, and everything seems good right now :)

**Comment by ferhatmelih** [comment]
can you please e-mail me from this address: melih.dal@eatron.com. 
I want to connect to your computer remotely try to see if I can help. 
thanks
