### ISSUE TITLE
msgpack rpc error

### ISSUE THREAD

**Issue by myxyzy** [blg604-proje/blg604-proje#6]
Hi, 

I have received below error, could not figure it out how to solve.

At initial setup, I received matplotlib and tornado sourced errors but downgraded both packages to given versions and reinstalled python api and tested.  tests are OK except last step(optional test).

![image](https://user-images.githubusercontent.com/44681416/87761114-96534a80-c819-11ea-8601-4149435dd2ef.png)
![image](https://user-images.githubusercontent.com/44681416/87761260-d1557e00-c819-11ea-9531-bf72863b53ed.png)

Thanks for your help.

**Comment by ferhatmelih** [comment]
Thanks for the detalied explanation. 

You need to install the new version from the google drive link. V1.5.3.D. This method is added in that release.

**Comment by myxyzy** [comment]
Thanks, 
Additionally .yml file needs to be updated with matplotlib, there might occur version mismatch with matplotlib and tornado by adding matplotlib afterward.

**Comment by ferhatmelih** [comment]
thanks for the feedback. I added matplotlib requirement that works correctly with the given tornado version.
