### ISSUE TITLE
Evaluate track gives inappropriate state shape

### ISSUE THREAD

**Issue by Alpkant** [blg604-proje/blg604-proje#8]
Hi, I train the network on Hungary track which gives me(23,) state shape. In the [evaluate.py](https://github.com/blg604-proje/blg604-proje/blob/master/examples/pytorch/evaluate.py) when I try with Austria track it gives me(4,) state shape and since the model input is not created with (4,) I get a shape mismatch error. Do I need to make an additional changes to adopt the model for different tracks or Austria track has some problems to give appropriate state shape?

**Comment by ferhatmelih** [comment]
I did not reproduce this. Can you please share the OS, and GPU specs?

**Comment by alisentas** [comment]
Hi, I and my teammate have this issue (I have Arch and he has Ubuntu 20.04). This does happen when track information is empty for the first few observations and only [speedX, speedY, angle and trackPos] are in the input vector.

**Comment by firatoncel** [comment]
You can use recently uploaded pickle files. It will solve the problem. @Alpkant

**Comment by ferhatmelih** [comment]
@firatoncel  thanks for the reply. I also added a safety layer for track sensor size in case that it does not return correct output. Retry number is increased from 1 to 100. then it returns error if the correct observation is not returned. I belive it can now tolerate that empty road returns. 

You can pull the latest code from repo for that.

**Comment by Alpkant** [comment]
Hi, I pulled the latest code and tried to use uploaded tracks, but now I get the following error. 

```
  File "/storage/deeprl_shared/SchumacherBehindtheWheel_RLProject/main/simstarEnv.py", line 196, in reset
    simstar_obs = self.get_simstar_obs(self.default_action)
  File "/storage/deeprl_shared/SchumacherBehindtheWheel_RLProject/main/simstarEnv.py", line 390, in get_simstar_obs
    if retry_counter> 100: raise RuntimeError("Track Sensor shape error. Exited")
RuntimeError: Track Sensor shape error. Exited
```
OS: Ubuntu 16.04 
GPU: Nvidia GTX TITAN  CUDA version: 9

**Comment by ferhatmelih** [comment]
Hi, I just installed the system from scratch and tested on a Ubuntu 16.04 system. Seems like there is a problem with Austria track retrieval at the moment. 

One solution is using the **Austria.pkl** file, as suggested by @firatoncel . 
I guess your specific problem could be that the realtive path of .pkl file is not right . So please check again that the **Austria.pkl** is your python path. 

I added an error raise to the place when Austria pickle is not found. Please delete an old pickle with the same name if there exists one.

**Comment by Alpkant** [comment]
Thank you @ferhatmelih and @firatoncel New Austria.pkl track solved the problem.
